{
  "exception_message": "division by zero",
  "exception_type": "ZeroDivisionError",
  "input_b64": "KysrICsrIDQvMA==",
  "input_preview": "+++ ++ 4/0",
  "seed": null,
  "target": "calc",
  "traceback": "Traceback (most recent call last):\n  File \"/home/king-del/Projects/Emmanuel/fuzzing-ci-tool/fuzz_tool/fuzzer.py\", line 318, in test_one_input\n    TARGET_FUNCS[ARGS.target](s)\n  File \"/home/king-del/Projects/Emmanuel/fuzzing-ci-tool/fuzz_tool/targets/app_calc.py\", line 83, in evaluate\n  File \"/home/king-del/Projects/Emmanuel/fuzzing-ci-tool/fuzz_tool/targets/app_calc.py\", line 24, in _eval\n    if isinstance(node, ast.Expression):\n  File \"/home/king-del/Projects/Emmanuel/fuzzing-ci-tool/fuzz_tool/targets/app_calc.py\", line 49, in _eval\n    # may raise ZeroDivisionError -> we WANT that to be unexpected\nZeroDivisionError: division by zero\n",
  "ts": 1756502576.203377
}